2023-06-10 22:08:20,161 Traceback (most recent call last):
  File "G:\My Drive\0-Main\pycontrol_api_v181\gui\configure_experiment_tab.py", line 138, in experiment_changed
    self.load_experiment(experiment_name)
  File "G:\My Drive\0-Main\pycontrol_api_v181\gui\configure_experiment_tab.py", line 244, in load_experiment
    with open(exp_path,'r', encoding='utf-8') as exp_file:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\My Drive\\0-Main\\pycontrol_api_v181\\experiments\\.json.json'

